### ISSUE TITLE
Training code/GPUs

### ISSUE THREAD

**Issue by zhang-lie** [aimagelab/safe-clip#1]
Nice work. Are you planning to release the training code of safe clip? Also, can you share how many/what GPUs you used for training, and how much time it took?

**Comment by federico1-creator** [comment]
Hi @zhang-lie, thank you for your interest in our work!

Currently, we do not have a roadmap for releasing the training code. However, I will keep you updated if there are any developments.
Regarding the hardware constraints, we used a single A100 GPU for 24 hours to compute the Safe-CLIP weights.

**Comment by tobiapoppi** [comment]
Hi @zhang-lie!

The training code for Safe-CLIP has just been released! 😃

You can find it in the repo and it's named [`safeclip_training.py`](https://github.com/aimagelab/safe-clip/blob/main/safeclip_training.py) (all necessary classes and modules are inside the `training` folder). The `.sh` training scripts (in sbatch format for usage with slurm) that can be used to start the training are in the [`sh_scripts`](https://github.com/aimagelab/safe-clip/tree/main/training/sh_scripts) folder.

Please, if you need further details or more insights on it, just open another issue!

Tobi
